# Random module
- __rand__ : Random values in given shape
- __randn__ : Returns sample/samples from "standard normal" distribution
- __randint__ : Returns random integers from low(inclusive) to high(exclusive)
- __random__ : Returns random floats in the half-open interval [0.0, 1.0)
- __choice__ : Generates random sample from a given 1-D array
- __shuffle__ : Shuffles the contents of a sequence

In [7]:
import numpy as np

a = np.arange(10)
print(a)
b = np.arange(10) + 5
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [10]:
np.random.shuffle(b)
print(b)
np.random.shuffle(b)
print(b)

[ 7  6 10  9 11 12 13  5 14  8]
[ 7  5 12  8  9 13 10  6 11 14]


In [14]:
a = np.random.rand(2,3)
print(a)

# Returns values from standart normal distribution
a = np.random.randn(2,3)
print(a)

[[ 0.08026518  0.16844818  0.58327174]
 [ 0.86528754  0.64580378  0.61145219]]
[[-0.19458006 -0.80572966  1.88318245]
 [ 1.07598021 -0.87383514  0.30276007]]


In [16]:
# 3 random ints in [5,10)
x = np.random.randint(5,10,3)
print(x)

[8 8 6]


In [17]:
# Randomly pick one element from array
print(np.random.choice([1,23,4,21,64]))

23


In [19]:
# Replicate(store the random machine)
# As it is preudo random
np.random.seed(1)