# Numpy
for mathematical operations

In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
a = np.array([[1],[2],[3],[4],[5]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [30]:
# Create array of zeros
print(np.zeros((3,3)))

# Create array of ones
print(np.ones((2,3)))

# Create array of constants
print(np.full((3,2),5))

# Identity matrix (square)
print(np.eye(4))

# Random matrix
rand = np.random.random((2,3))
print(rand)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[5 5]
 [5 5]
 [5 5]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.28446511  0.49176355  0.11046396]
 [ 0.21218763  0.54696417  0.18904355]]


In [31]:
# [row range, col range]
print(rand[ : , 1 ])

[ 0.49176355  0.54696417]


In [32]:
# Slicing
rand[1,1:3] = 1
print(rand)

[[ 0.28446511  0.49176355  0.11046396]
 [ 0.21218763  1.          1.        ]]


In [34]:
# Set rows and columns with any value
z = np.zeros((3,3))
print(z)
# First row
z[1,:] = 10
# Last col
z[:,-1] = 5
print(z)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[  0.   0.   5.]
 [ 10.  10.   5.]
 [  0.   0.   5.]]


In [35]:
print(z.dtype)

float64


In [36]:
w = np.zeros((3,3), dtype=int)
print(w.dtype)

int64


## Mathematical Operations

In [40]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Element wise addition/subtraction 
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [42]:
# Matric multiplication/Dot Product
print(x)
print(y)
print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [60]:
# Multiplication(Dot product) of Vectors -> Scalar
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))

30


In [61]:
print(a)
print(sum(a))

[1 2 3 4]
10


In [62]:
print(x)
print(np.sum(x))
print()
print(np.sum(x,axis=0))
print()
print(np.sum(x,axis=1))

[[1 2]
 [3 4]]
10

[4 6]

[3 7]


In [63]:
# Stacking of arrays
print(a)
b **= 2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [64]:
np.stack((a,b), axis=1)

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [65]:
g = np.stack((a,b), axis=0)

In [66]:
# Reshape Numpy Array
print(g)
g = g.reshape((4,2))
print(g)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [67]:
g = g.reshape((8,1))
print(g)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [72]:
# No. of columns can be left behind
print(g.reshape((4,-1)))

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [73]:
# No. of rows can be left behind
print(g.reshape((-1,4)))

[[ 1  2  3  4]
 [ 1  4  9 16]]
