# Linear Algebra
Using numpy

## 1. Scalars and Vectors
- __Scalar__ : is a single number
- __Vector__ : is an array of scalars

In [6]:
import numpy as np

In [3]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


In [4]:
# Vector as column
x2 = np.array([[4],[5],[6]])
print(x2)
print(x2.shape)
print(x2[0][0])

[[4]
 [5]
 [6]]
(3, 1)
4


In [6]:
x3 = np.array([[4],[5],[6],[7]])
x = x3.reshape((-1,2))
print(x)
print(x.shape)

[[4 5]
 [6 7]]
(2, 2)


## 2. Matrices and Tensors
- __Matrix__ : is a 2D array of scalars
- __Tensor__ : is an array with __more than 2__ axes

In [9]:
# Matrix
X = np.array([[4,5,6],[10,11,12],[15,16,17]])
print(X)
print(X.shape)
print(X[1][1])
X[1:, :] = 2
print(X)

[[ 4  5  6]
 [10 11 12]
 [15 16 17]]
(3, 3)
11
[[4 5 6]
 [2 2 2]
 [2 2 2]]


In [10]:
# Tensor
X = np.array([[[4,5,6],[10,11,12]],[[1,2,0],[15,16,17]]])
print(X)
print(X.shape)

[[[ 4  5  6]
  [10 11 12]]

 [[ 1  2  0]
  [15 16 17]]]
(2, 2, 3)


## 3. Transpose
![Transpose](https://wikimedia.org/api/rest_v1/media/math/render/svg/9b0864ad54decb7f1b251512de895b40545facf5)

In [18]:
print(x)
xt = np.transpose(x)
print(xt)

[[4 5]
 [6 7]]
[[4 6]
 [5 7]]


In [21]:
y = x.reshape((-1,1))
print(y)
print(y.shape)
y = np.transpose(y)
print(y)
print(y.shape)

[[4]
 [5]
 [6]
 [7]]
(4, 1)
[[4 5 6 7]]
(1, 4)


## 4. Broadcasting
- Add scalar to numpy array
- Add vector to matrix(adds vector to each column of matrix)

In [28]:
l = [1,2,3,4]
# Gives error
# l = l+1
l = np.array(l)
l = l+1
print(l)
l = l**2 + 1
print(l)
print(np.sqrt(l))

[2 3 4 5]
[ 5 10 17 26]
[ 2.23606798  3.16227766  4.12310563  5.09901951]


In [29]:
l2 = np.array([[1,2,3],[4,5,6]])
l2 += [0,1,2]
print(l2)

[[1 3 5]
 [4 6 8]]


## 5. Matrix Multiplication
![Matrix Multiplication](https://wikimedia.org/api/rest_v1/media/math/render/svg/3cfeccef1c8c7e6da0ddf08daed8dbf3c6f50c5e)
![Matrix Multiplication Linear Combination](https://lh5.googleusercontent.com/proxy/DfkuHP_L81Bz0LZ-6G6YOC8lbUGe943MAlG49ST5xvzvXY63ViEHR4PWOKHwF0RSHgAOMeE462BuHWRqM2n4MrPjdc4=w506-h303-p)


In [3]:
X = np.array([[4,5,6],[10,11,12],[15,16,17]])
Y = np.array([[40,50,70],[110,121,123],[115,163,157]])
prod = np.dot(X,Y)
print(prod)

[[1400 1783 1837]
 [2990 3787 3937]
 [4315 5457 5687]]


## 6. Element Wise Multiplication: Hadamard product

In [5]:
X = np.array([[4,5,6],[10,11,12],[15,16,17]])
Y = np.array([[1,2,3],[2,3,4],[5,4,3]])
prod = X*Y
# prod[i][j] = X[i][j] * Y[i][j] 
print(prod)

[[ 4 10 18]
 [20 33 48]
 [75 64 51]]


## 7. Norm
- Thought as proxy for size of vector.
![Norm](http://slideplayer.com/slide/6132850/18/images/1/Vector+Norms+DEF%3A+A+norm+is+a+function+that+satisfies.jpg)

In [7]:
x = np.array([-5,3,10])

In [8]:
lp2 = np.linalg.norm(x)
print(lp2)

11.5758369028


In [10]:
lp1 = np.linalg.norm(x, ord=1)
print(lp1)

18.0


In [11]:
lpinf = np.linalg.norm(x, ord=np.inf)
print(lpinf)

10.0
