# Linear Algebra
Using numpy

## 1. Scalars and Vectors
- __Scalar__ : is a single number
- __Vector__ : is an array of scalars

In [1]:
import numpy as np

In [3]:
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


In [4]:
# Vector as column
x2 = np.array([[4],[5],[6]])
print(x2)
print(x2.shape)
print(x2[0][0])

[[4]
 [5]
 [6]]
(3, 1)
4


In [6]:
x3 = np.array([[4],[5],[6],[7]])
x = x3.reshape((-1,2))
print(x)
print(x.shape)

[[4 5]
 [6 7]]
(2, 2)


## 2. Matrices and Tensors
- __Matrix__ : is a 2D array of scalars
- __Tensor__ : is an array with __more than 2__ axes

In [9]:
# Matrix
X = np.array([[4,5,6],[10,11,12],[15,16,17]])
print(X)
print(X.shape)
print(X[1][1])
X[1:, :] = 2
print(X)

[[ 4  5  6]
 [10 11 12]
 [15 16 17]]
(3, 3)
11
[[4 5 6]
 [2 2 2]
 [2 2 2]]


In [10]:
# Tensor
X = np.array([[[4,5,6],[10,11,12]],[[1,2,0],[15,16,17]]])
print(X)
print(X.shape)

[[[ 4  5  6]
  [10 11 12]]

 [[ 1  2  0]
  [15 16 17]]]
(2, 2, 3)


## 3. Transpose
![Transpose](https://wikimedia.org/api/rest_v1/media/math/render/svg/9b0864ad54decb7f1b251512de895b40545facf5)

In [18]:
print(x)
xt = np.transpose(x)
print(xt)

[[4 5]
 [6 7]]
[[4 6]
 [5 7]]


In [21]:
y = x.reshape((-1,1))
print(y)
print(y.shape)
y = np.transpose(y)
print(y)
print(y.shape)

[[4]
 [5]
 [6]
 [7]]
(4, 1)
[[4 5 6 7]]
(1, 4)


## Broadcasting
- Add scalar to numpy array
- Add vector to matrix(adds vector to each column of matrix)

In [28]:
l = [1,2,3,4]
# Gives error
# l = l+1
l = np.array(l)
l = l+1
print(l)
l = l**2 + 1
print(l)
print(np.sqrt(l))

[2 3 4 5]
[ 5 10 17 26]
[ 2.23606798  3.16227766  4.12310563  5.09901951]


In [29]:
l2 = np.array([[1,2,3],[4,5,6]])
l2 += [0,1,2]
print(l2)

[[1 3 5]
 [4 6 8]]
